# applied automatically by https://github.com/Faithlife/RepoConventionsApplier (DO NOT REMOVE THIS LINE)
conventions:
  - path: Faithlife/CodingGuidelines/conventions/faithlife-auto-apply-conventions
  - path: Faithlife/CodingGuidelines/conventions/dotnet-common
  - path: Faithlife/CodingGuidelines/conventions/faithlife-dotnet-library-build
  - path: Faithlife/CodingGuidelines/conventions/faithlife-dotnet-library-workflow
  - path: Faithlife/CodingGuidelines/conventions/faithlife-license-mit

pull-request:
  reviewers:
    - ejball
