version: '{build}'
image: Visual Studio 2017
environment:
  NUGETAPIKEY:
    secure: hPo98uWApLeubFt4LvY7wXpLKExUDaQbtzn4qCKXTq2C4wH2H9K3dFusJDLMTaff
build_script:
- ps: .\build.ps1 --target=NuGetPublish """--trigger=$env:APPVEYOR_REPO_TAG_NAME""" "--nugetApiKey=$env:NUGETAPIKEY"
test: off
