name: Build

on:
  push:
    branches: [master]
    tags-ignore: ['**']
  pull_request:
  workflow_dispatch:

env:
  DOTNET_NOLOGO: 1
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

defaults:
  run:
    shell: pwsh

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Install .NET
      uses: actions/setup-dotnet@v3
    - name: Check out code
      uses: actions/checkout@v3
    - name: Restore
      run: .\build.ps1 restore
    - name: Build
      run: .\build.ps1 build --skip restore
    - name: Test
      run: .\build.ps1 test --skip build
    - name: Publish
      if: runner.os == 'Windows' && github.repository_owner == 'Faithlife' && github.ref == 'refs/heads/master'
      env:
        BUILD_BOT_PASSWORD: ${{ secrets.BUILD_BOT_PASSWORD }}
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: .\build.ps1 publish --skip test
